language: ruby
rvm:
  - 2.0.0
env:
  - DB=mysql
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database namie_analytics_test'
script:
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake
